Support svg2png being used in a command pipe

diff --git a/svg2png b/svg2png
--- a/svg2png
+++ b/svg2png
@@ -1,61 +1,86 @@
 #!/bin/bash -e
 
-if [[ $# == 0 || $1 == "-h" || $1 == "--help" ]]; then
-  echo "Usage: svg2png FILE.svg [FILE.svg...] [WIDTH]"
-  echo "       svg2png FILE.svg FILE.png [WIDTH]"
-  exit 0
-fi
+TMP=$(mktemp -d)
 
+trap 'rm -rf "$TMP"' EXIT
+
+show_help () {
+  echo "Usage: svg2png [FILE.svg...] [WIDTH]"
+  echo "       svg2png [FILE.svg] FILE.png [WIDTH]"
+  echo ""
+  echo "If no SVG file, read standard input and write to"
+  echo "standard output or PNG file."
+  exit 0
+}
+
+show_err () {
+  >&2 echo "*** ERROR: $1"
+  exit 1
+}
+
+command -v inkscape >/dev/null 2>&1 || show_err "inkscape command not found"
+
+PIPE=
 SVG=()
 PNG=
 WIDTH=
 
 while [ $# != 0 ]; do
-  if [[ $1 == *.svg ]]; then
+  if [[ $1 == "-h" || $1 == "--help" ]]; then
+    show_help
+  elif [[ $1 == *.svg ]]; then
     if [[ $PNG != "" ]]; then
-      >&2 echo "*** ERROR: An svg file cannot be given after the png file"
-      exit 1
+      show_err "An svg file cannot be given after the png file"
     fi
     SVG+=("$1")
   elif [[ $1 == *.png ]]; then
-    if [[ ${#SVG[@]} != 1 ]]; then
-      >&2 echo "*** ERROR: Exactly one svg file must be given before the png file"
-      exit 1
+    if [[ ${#SVG[@]} -gt 1 ]]; then
+      show_err "Multiple svg files cannot be given before the png file"
     fi
     if [[ $PNG != "" ]]; then
-      >&2 echo "*** ERROR: Only one png file can be given"
-      exit 1
+      show_err "Only one png file can be given"
     fi
     PNG=$1
   elif [[ $1 =~ ^[1-9][0-9]*$ ]]; then
     if [[ $WIDTH != "" ]]; then
-      >&2 echo "*** ERROR: Only one width can be given"
-      exit 1
+      show_err "Only one width can be given"
     fi
     WIDTH=$1
   else
-    >&2 echo "*** ERROR: Invalid argument(s)"
-    exit 1
+    show_err "Invalid argument ($1)"
   fi
   shift
 done
 
 if [[ ${#SVG[@]} == 0 ]]; then
-  >&2 echo "*** ERROR: At least one svg file must be given"
-  exit 1
+  PIPE=1
+  SVG+=("-")
 fi
 
-for SF in "${SVG[@]}"; do
-  DF=${PNG}
-  if [[ $DF == "" ]]; then
-    DF=${SF/%.svg/.png}
+for SVG_FILE in "${SVG[@]}"; do
+  SF="$SVG_FILE"
+  if [[ $PIPE == 1 ]]; then
+    SF="$TMP/input.svg"
+    cat - >"$SF"
   fi
-  echo ${DF}
-  CMD='inkscape -o "${DF}"'
-  if [[ $WIDTH != "" ]]; then
-    CMD+=" --export-width=${WIDTH}"
+
+  DF="${PNG:-${SF/%.svg/.png}}"
+  if [[ $PIPE == 1 && $PNG == "" ]]; then
+    DF="$TMP/output.png"
   fi
-  CMD+=' "${SF}"'
-  # Cannot trust error code or stderr behavior from inkscape.
-  eval ${CMD} 2> >(grep -vP '^(Background|Area) ' >&2) || :
+
+  if [[ $PIPE != 1 ]]; then
+    >&2 echo "$DF"
+  fi
+
+  ARGS=("$SF")
+  ARGS+=(--export-filename="$DF")
+  [[ $WIDTH != "" ]] && ARGS+=(--export-width="$WIDTH")
+
+  # Cannot trust error code from inkscape.
+  inkscape "${ARGS[@]}" 2> >(grep -vP '^(Background|Area) ' >&2) || :
+
+  if [[ $PIPE == 1 && $PNG == "" ]]; then
+    cat "$DF"
+  fi
 done
